language: node_js
node_js:
  - "12"

# before_cache:
#   - brew cleanup

cache: npm

# cache:
#   directories:
#     - $HOME/Library/Caches/Homebrew

matrix:
  fast_finish: true
  include:
    - os: osx
      osx_image: xcode12
      # osx_image: xcode9.1
      env: TEST_COMMAND=test
    - os: linux
      dist: trusty
      env: TEST_COMMAND=test

addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - gcc-4.9
      - g++-4.9

before_install:
  - if [ "$CXX" = "g++" ]; then export CXX="g++-4.9" CC="gcc-4.9"; fi
  - echo $TRAVIS_OS_NAME
  - export PATH="${PATH}:node_modules/.bin"
  - |
    if [ "$TRAVIS_OS_NAME" = "osx" ]; then
      curl -LO https://github.com/neovim/neovim/releases/download/nightly/nvim-macos.tar.gz
      tar xzf nvim-macos.tar.gz
      export PATH="${PATH}:$(pwd)/nvim-osx64/bin"

      curl -LO https://github.com/tree-sitter/tree-sitter-ruby/releases/download/v0.19.0/tree-sitter-ruby-v0.19.0-node-v64-darwin-x64.tar.gz
      tar xzf tree-sitter-ruby-v0.19.0-node-v64-darwin-x64.tar.gz
      mv build/Release/tree_sitter_ruby_binding.node test/dependencies/parser/ruby.so

      curl -LO https://github.com/BurntSushi/ripgrep/releases/download/13.0.0/ripgrep-13.0.0-x86_64-apple-darwin.tar.gz
      tar xzf ripgrep-13.0.0-x86_64-apple-darwin.tar.gz
      export PATH="${PATH}:$(pwd)/ripgrep-13.0.0-x86_64-apple-darwin"
    else
      curl -LO https://github.com/neovim/neovim/releases/download/nightly/nvim-linux64.tar.gz
      tar xzf nvim-linux64.tar.gz
      export PATH="${PATH}:$(pwd)/nvim-linux64/bin"

      # curl -LO https://github.com/tree-sitter/tree-sitter-ruby/releases/download/v0.19.0/tree-sitter-ruby-v0.19.0-electron-v64-linux-x64.tar.gz
      # tar xzf tree-sitter-ruby-v0.19.0-electron-v64-linux-x64.tar.gz
      # mv build/Release/tree_sitter_ruby_binding.node test/dependencies/parser/ruby.so

      # curl -LO https://github.com/tree-sitter/tree-sitter-ruby/releases/download/v0.19.0/tree-sitter-ruby-v0.19.0-node-v64-linux-x64.tar.gz
      # tar xzf tree-sitter-ruby-v0.19.0-node-v64-linux-x64.tar.gz
      # mv build/Release/tree_sitter_ruby_binding.node test/dependencies/parser/ruby.node

      curl -LO https://github.com/BurntSushi/ripgrep/releases/download/13.0.0/ripgrep-13.0.0-x86_64-unknown-linux-musl.tar.gz
      tar xzf ripgrep-13.0.0-x86_64-unknown-linux-musl.tar.gz
      export PATH="${PATH}:$(pwd)/ripgrep-13.0.0-x86_64-unknown-linux-musl"

      # curl -LO https://github.com/BurntSushi/ripgrep/releases/download/13.0.0/ripgrep_13.0.0_amd64.deb
      # sudo dpkg -i ripgrep_13.0.0_amd64.deb
    fi
  - echo $PATH
  - rg --version
  - nvim --version
  - pwd

install:
  - npm install
  - nvim --headless -u "test/helpers/vimrc" -c "TSInstall ruby" -c "q"

script:
  - export NODE_ENV=test
  - npm run $TEST_COMMAND

notifications:
  email:
    on_success: never
    on_failure: never
    on_cancel: never
    on_error: never
